export const BLOG_ARTICLES = [
  {
    slug: "zzp-zorg-belastingaangifte-2025",
    title: "ZZP in de zorg: belastingaangifte 2025 stap voor stap",
    excerpt: "De belastingaangifte als ZZP'er in de zorg hoeft geen nachtmerrie te zijn. Met de juiste voorbereiding en kennis van aftrekposten houd je meer over van wat je verdient.",
    category: "ZZP Tips",
    readTime: "8 min",
    date: "14 april 2026",
    emoji: "📋",
  },
  {
    slug: "big-nummer-aanvragen-gids",
    title: "BIG-nummer aanvragen: de complete gids voor nieuwe zorgprofessionals",
    excerpt: "Zonder BIG-registratie geen werk in de zorg. Ontdek stap voor stap hoe je jouw registratie aanvraagt, hoe lang het duurt en wat je nodig hebt.",
    category: "Wet & Regelgeving",
    readTime: "6 min",
    date: "10 april 2026",
    emoji: "🏥",
  },
  {
    slug: "flexibel-werken-zorg-voordelen",
    title: "5 voordelen van flexibel werken in de zorg die niemand je vertelt",
    excerpt: "Meer vrijheid, hogere inkomsten en meer variatie in je werk — flexibel werken in de zorg heeft meer voordelen dan je denkt. We zetten ze eerlijk op een rij.",
    category: "Arbeidsmarkt",
    readTime: "4 min",
    date: "7 april 2026",
    emoji: "⚡",
  },
  {
    slug: "zzp-tarief-berekenen-zorg",
    title: "Zo bereken je jouw uurtarief als ZZP'er in de zorg",
    excerpt: "Te laag zitten kost je geld, te hoog en je wordt overgeslagen. Met deze formule bereken je een eerlijk, marktconform uurtarief voor jouw functie en regio.",
    category: "ZZP Tips",
    readTime: "5 min",
    date: "3 april 2026",
    emoji: "💰",
  },
  {
    slug: "ai-planning-zorg-2025",
    title: "AI in zorgplanning: hoe technologie het personeelstekort aanpakt",
    excerpt: "Slimme algoritmes matchen zorgprofessionals en instellingen sneller dan ooit. Maar wat betekent AI-gedreven planning voor de mens achter de dienst?",
    category: "Zorg & Technologie",
    readTime: "7 min",
    date: "29 maart 2026",
    emoji: "🤖",
  },
  {
    slug: "burnout-voorkomen-zzp-zorg",
    title: "Burnout voorkomen als ZZP'er in de zorg: praktische tips",
    excerpt: "Als ZZP'er draag je alle verantwoordelijkheid zelf — inclusief je eigen welzijn. Dit zijn de signalen, oorzaken en effectieve strategieën om burnout voor te blijven.",
    category: "Arbeidsmarkt",
    readTime: "5 min",
    date: "24 maart 2026",
    emoji: "🧘",
  },
];
